### ISSUE TITLE
Update Favicon to new logo

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one-express#9]
## Summary
Use the new logo as the default favicon in the template

### Notes
- Not sure if we can, but using the svg here would be awesome, since it's all high-res and stuff

**Comment by tmjoseantonio** [comment]
Greetings, 

I would like to contribute to your project doing this small update. In order to do that I would like to know a couple of things:
- Do you have any browser restriction for the favicon? (i.e. Internet Explorer)
- Are these the right assets?  https://github.com/Tram-One/tram-logo/tree/master/v3

**Comment by JRJurman** [comment]
@tmjoseantonio thanks for the interest!
It should work in the latest version of every browser (but since this is a generator, it's not THAT important that it works everywhere... (I imagine the favicon will be one of the things replaced often).

And yes, v3 is the correct folder!

**Comment by JRJurman** [comment]
resolved by #10
